[package]
name = "tonguetoquill-personal-letter"
version = "0.1.0"
compiler = "0.14.0"
entrypoint = "src/lib.typ"
authors = ["Airmark"]
license = "Apache-2.0"
description = "Typeset personal letters compliant with AFH 33-337 'The Tongue and Quill' Chapter 15."
keywords = [
    "USAF",
    "Air Force",
    "personal letter",
    "military",
    "AFH 33-337",
    "official",
    "correspondence",
]
categories = ["office", "report"]
disciplines = ["politics", "law", "business", "engineering", "education"]
