[package]
name = "tonguetoquill-personal-letter"
version = "0.1.0"
compiler = "0.14.0"
entrypoint = "src/lib.typ"
repository = "https://github.com/tonguetoquill/airmark-quiver"
authors = ["Nibs"]
license = "MIT"
description = "Typeset personal letters that comply with AFH 33-337 'The Tongue and Quill'."
keywords = [
    "USAF",
    "Air Force",
    "personal letter",
    "letter",
    "military",
    "AFH 33-337",
    "official",
    "correspondence",
    "formatting",
]
categories = ["office"]
disciplines = ["politics", "law", "business", "education"]
